language: java
dist: xenial
jdk: openjdk11
services: xvfb
addons:
  sonarcloud:
    organization: "sreenu-reddy"
    token:
      secure: "pK9UiU74Dub7zjrkJpqPjNLFxA9KqtGw841gF1+2y9ATdRRvury843/EuyOw6QWIBPPDKiba9JYPmB8pNlidE1Pscx9w9TkySpi3EJBl4S6nYunbfb7lONnakonmrwurBSwfdCi8WN9vY+j4o+dsq7eaonLJZ8EwtO0Ir5xvpdfMYxs4Fi2MxtdIuMO2FRysBOstDIwrRyBgU9sjbWHOgl51fN9nu2e+ob+vUH/QlCfd9qqBF4Uta5YtY2yXwnwcwNPjWEJXtMpYpOYlTKStFjI4rllgrodaC8/GVmmQW5rsRqBHBl+3OqUwtA0foChB7rOR+kJSwr7DwdURHDXhz3Ole9qSOcSl6qvEwW6WoAlLuF5YftiM1To1BdVtZkqnevSGvTl16kpla+JweuVGfkBpHdmNrfU3dUNafyP403gKCguBQEQLiVQxvytl8R+sMpaxrDb4Y/vdNuQ04uoIoZVpxKUBIN70FATth4zSfl8R9Gw7NHHuq10XGv6D5HOrvF1N0CIwe+lNmFeDoFEA4rrfswj1ahchHPMX3gu1o8d28Y6xVTDnA5GTHl09jdcFycC7HRH0JDz9p5PYND50VQ4hi4+SQwRElPYtueFtCWAYJ8MAT0gbyT7kymMmEajTKlRbEOTY6RqYkVDRiDjd8YZuD1D2956weXdGMMqp4Kc="


after_success:
  - mvn clean test jacoco:report coveralls:report
install: true
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.sonar/cache"
script:
    - mvn clean install jacoco:report coveralls:report sonar:sonar  -Dsonar.projectKey=sreenu-reddy_ppm
env:
  global:
    secure: "Y0E2Beg7w+39ljEs/g7OYeQVMWaGRhSI1vQyaMHQ3V/rhkI3LF2ib+nlt/okNlul6uY8/vnuzERbwukrR0BnXlI7I5GkHB4XZe4NJ1GnulZYaVv4gvkYRwYWwYr/EdDpMVkD24RsiJpWTYA9hUDV6ZJXnb1F+o4euntvsuY6UZgOv3+blojhN6Z3VBwrJ3cCZ/mxy3s0SuCaVYLCoeIwo9K0At566d5Bv/cNrzsksSEEBkjfv5v2cL/yADgytD5lFQAMJY73etVTzw8MO+jTslDpeJnlLlO7Kw8HtbHGWes0jRKskNbGgc32+aswlEJyWHPA6687SgQO/C2MvfH2IJvyh3jKXFGWV7/tLIdfkUxM+2+P1+Cgod/7kZpFuU4fsKuePjwGwqJerdr40428idd12LOZfJ6B9uancYzsGYJDek1PyKcXi5A28L2KdlO9avOZ/hn4QTxjrR/yvIVT090jahe0nhOv2LXtK/BQuTPmfV+Dg3UMrRST5JOtWKfLDeJDV99lGkcfG0oFzi3T5ZXJR5AKVLAIvzB9ImdiL6uIh6fELDiVjlH0sQ/aY7prT2BOjruoUzDxICwSQgMfThA7HnC/r+4s3yVwVeTAumUgCs8fJXO18r7/1/JdyIxbJv/KrZKvZIFvFIxbf5wIcBJrVjV+o+9vAZ3yt8QYnXk="
