spring:
  datasource:
    url: jdbc:mysql://localhost:3303/ppm_prod
    username: ppm_prod_user
    password: ppmv1
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false